name: CI pipeline to automate deployment

on:
  push:
    branches:
      - dev
      - main
    paths-ignore:
      - '**/*.md'
      - '.devcontainer/**'
      - 'assets/**'
  
jobs:

  # job-1: Perform security scans to check any secret leaks, find vulnerability within code and generate SBOM for tracking packages
  security-scan:
    runs-on: ubuntu-latest

    permissions:
      contents: write # write permission is required for trivy SBOM
      issues: write # required by oke-py for npm audit
      pull-requests: write # required by oke-py for npm audit
      security-events: write # this permission is required for trivy FS and docker image scan

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # disable shallow clone => full repo clone, 0 indicates all history to fetch for all branches and tags

      - name: Setup node v20
        uses: actions/setup-node@v6
        with:
          node-version: '20'   # selected compatible LTS version based on reactjs "^18.3.1" version from package.json
          cache: 'npm'

      ######### Check secret leaks using GitLeaks ##########

      - name: Check secret leaks
        uses: gitleaks/gitleaks-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITLEAKS_NOTIFY_USER_LIST: '@harshitrajsinha' # send notiification to the user if leaks detected (need to enable notification settings on account)

      ######## Install dependencies ###########    
      - name: Install dependencies
        run: npm ci

      ######### Check package vulnerability ##########

        ## Perform npm audit (development only) for SCA
      - name: Check vulnerability (development env)
        if: github.ref == 'refs/heads/dev'
        uses: oke-py/npm-audit-action@v4
        with:
          audit_level: high
          github_token: ${{ secrets.GITHUB_TOKEN }}
          issue_labels: vulnerability,test  # these labels are used when vulnerability report is created as an issue on GitHub
          create_issues: true
      - name: Display audit report
        if: always() && github.ref == 'refs/heads/dev'
        run: npm audit --audit-level=high || true
      
      ## Perform File system scan using Trivy (production only)

      - name: Filesystem scan
        if: github.ref == 'refs/heads/main'
        uses: aquasecurity/trivy-action@v0.36.0
        with:
          scan-type: "fs"
          scan-ref: .
          scanners: vuln,secret,misconfig
          format: table                   # change to json when need to upload as an artifact
          # output: trivy-report.json
          severity: 'CRITICAL,HIGH'
          ignore-unfixed: true
          exit-code: 1

      # - name: Upload Trivy FS report
      #   if: always() && github.ref == 'refs/heads/main'
      #   uses: actions/upload-artifact@v4
      #   with:
      #     name: trivy-fs-report
      #     path: trivy-report.json
          # retention-days: 30
      
      ## Generate SBOM using Trivy (production only)  --- Need to enable dependency graph: https://docs.github.com/en/code-security/how-tos/secure-your-supply-chain/secure-your-dependencies/enabling-the-dependency-graph

      - name: Trivy SBOM
        if: github.ref == 'refs/heads/main'
        uses: aquasecurity/trivy-action@v0.36.0
        with:
          scan-type: 'fs'
          format: 'github'
          output: 'dependency-results.sbom.json'
          scan-ref: '.'
          github-pat: ${{ secrets.GITHUB_TOKEN }}

      ######### Perform code analysis ##########
      
        ## Perform SonarQube (production only) for SAST
      - name: SonarQube SAST
        if: github.ref == 'refs/heads/main'
        uses: SonarSource/sonarqube-scan-action@v8.1.0
        with:
          args: >     # using args rather than creating sonar-project.properties file for easy accessibility (sonarqube recommends to create file)
            -Dsonar.projectKey=reactflix-devops
            -Dsonar.sources=src
            "-Dsonar.projectName=ReactFlix"
            -Dsonar.verbose=true
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
          
  # job-2: Perform linting to check erros in code syntax and code style
  linting:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      issues: write
      pull-requests: write
      packages: read
      statuses: write

    steps:
      - name: Check Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup node v20
        uses: actions/setup-node@v6
        with:
          node-version: '20'
          cache: npm

      - name: Check linting
        uses: super-linter/super-linter@v8.6.0
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
          DEFAULT_BRANCH: main

  # unit-test: 

  # job-3: Perform docker image build, scan and release
  image-build-and-release:
    needs: [security-scan]
    runs-on: ubuntu-latest
    
    permissions:
      contents: read
      security-events: write

    env:
      IMAGE_NAME: harshitrajsinha/reactflix
      IMAGE_TAG: ${{ github.sha }}
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup node v20
        uses: actions/setup-node@v6
        with:
          node-version: '20'   
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build app for fast fail (if)
        run: npm run build
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      
      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME}}
          password: ${{ secrets.DOCKERHUB_TOKEN}}
      
      ## Build docker image

      - name: Build image
        uses: docker/build-push-action@v6
        with:
          context: .
          secret: id=movies-app-secrets[,src=.env]
          file: docker/Dockerfile
          tags: ${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG}}
          load: true
          push: false
          cache-from: type=gha
          cache-to: type=gha,mode=max

      ## Scan docker image using Docker Scout (development only)

      - name: Scan image via Docker scout
        if: github.ref == 'refs/heads/dev'
        uses: docker/scout-action@v1
        with:
          command: cves
          image: ${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}
          only-severities: critical
          exit-code: true
          sarif-file: sarif.output.json
          summary: true
      - name: Upload docker scout report
        if: always() && github.ref == 'refs/heads/dev'
        uses: actions/upload-artifact@v4
        with:
          name: docker-scout-report
          path: sarif.output.json
      
      ## Scan docker image using Trivy (production only)

      - name: Trivy image scan
        if: github.ref == 'refs/heads/main'
        uses: aquasecurity/trivy-action@v0.36.0
        with:
          image-ref: ${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}
          format: sarif
          output: trivy-image-results.sarif
          severity: 'CRITICAL'
          ignore-unfixed: true
          exit-code: 1
      - name: Upload trivy image scan artifact
        if: always() && github.ref == 'refs/heads/main'
        uses: actions/upload-artifact@v4
        with:
          name: trivy-image-scan-report
          path: trivy-image-results.sarif
      - name: Upload trivy image scan SARIF report
        if: always() && github.ref == 'refs/heads/main' 
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: trivy-image-results.sarif

      ## Release the docker image to registry for deployment pipeline
      - name: Push image
        run: |
          docker push $IMAGE_NAME:$IMAGE_TAG
