name: CI pipeline to automate deployment

on:
  push:
    branches:
      - dev
    paths-ignore:
      - '**/*.md'
  
jobs:

  security-scan:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      issues: write
      pull-requests: write

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup node v24
        uses: actions/setup-node@v6
        with:
          node-version: '24'
          cache: npm

      - name: Check secret leaks
        uses: gitleaks/gitleaks-action@v24
      
      - name: Install dependencies
        run: npm ci

      - name: Check vulnerability
        uses: oke-py/npm-audit-action@v4
        with:
          audit_level: high
          github_token: ${{ secrets.GITHUB_TOKEN }}
          issue_labels: vulnerability,test
          create_issues: true
  # linting:

  # image-build-and-release: